services:
  # -----------------------------------------------------------------
  # SERVIÇO 1: Banco de Dados (PostgreSQL)
  # -----------------------------------------------------------------
  db:
    image: postgres:latest
    container_name: ans-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres2018!
      POSTGRES_DB: ans_db
    ports:
      - "5432:5432"
    volumes:
      # Mapeia os CSVs locais para dentro do container
      - ./csv:/tmp/csv_data
      # Executa o script SQL automaticamente na primeira inicialização
      - ./sql:/docker-entrypoint-initdb.d/
      # Persiste os dados do banco para não perder ao desligar
      - ./postgres_data:/var/lib/postgresql
    networks:
      - ans-network

  # -----------------------------------------------------------------
  # SERVIÇO 2: Interface Gráfica (pgAdmin 4)
  # -----------------------------------------------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: teste-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: thiago_silva.9@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: PgAdmin2018!
    ports:
      - "15432:80" # Acessar no navegador via http://localhost:15432
    depends_on:
      - db # Garante que o pgAdmin inicie sabendo que o banco existe
    networks:
      - ans-network
    volumes:
      # Opcional: Salva suas configurações de servidor do pgAdmin
      - pgadmin_data:/var/lib/pgadmin

# Definição dos Volumes Persistentes
volumes:
  postgres_data:
  pgadmin_data:

# Definição da Rede (para eles se enxergarem)
networks:
  ans-network:
    driver: bridge