services:
  # -----------------------------------------------------------------
  # SERVIÇO 1: Banco de Dados (PostgreSQL)
  # -----------------------------------------------------------------
  db:
    image: postgres:latest
    container_name: ans-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres2018!
      POSTGRES_DB: ans_db
    ports:
      - "5432:5432"
    volumes:
      # Mapeia os CSVs locais para dentro do container
      - ./backend/csv:/tmp/csv_data
      # Executa o script SQL automaticamente na primeira inicialização
      - ./backend/sql:/docker-entrypoint-initdb.d/
      # Persiste os dados do banco para não perder ao desligar
      - ./backend/postgres_data:/var/lib/postgresql
    networks:
      - ans-network

  # -----------------------------------------------------------------
  # SERVIÇO 2: Interface Gráfica (pgAdmin 4)
  # -----------------------------------------------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: teste-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: thiago_silva.9@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: PgAdmin2018!
    ports:
      - "15432:80"
    depends_on:
      - db # Garante que o pgAdmin inicie sabendo que o banco existe
    networks:
      - ans-network
    volumes:
      # Salva suas configurações de servidor do pgAdmin
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build: ./backend 
    container_name: ans-api
    ports:
      - "8000:8000"  
    environment:
      # Conecta ao host 'db' na porta 5432
      DATABASE_URL: postgresql+asyncpg://postgres:Postgres2018!@db:5432/ans_db
    depends_on:
      - db            # Espera o banco subir antes de iniciar a API
    networks:
      - ans-network
  
  frontend:
    build: ./frontend      
    container_name: ans-frontend
    ports:
      - "3001:5173"       
    volumes:
      - ./frontend:/app   
      - /app/node_modules 
    environment:
      - VITE_API_URL=http://localhost:8000/api 
    depends_on:
      - backend             # Espera a API subir antes
    networks:
      - ans-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  ans-network:
    driver: bridge